name: Deploy first Flask App with GitHub Actions on Debian server

on:
  push:
    branches:
      - main  # Déclencher l'action sur push dans main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH and Deploy
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.SSH_PRIVATA_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          ssh-keyscan -H kascali.de >> /home/runner/.ssh/known_hosts

          ssh -i /home/runner/.ssh/id_rsa -o StrictHostKeyChecking=no user@kascali.de << 'EOF'
            cd /var/www/Example-CI-CD-Github-Action
            git pull origin main
            source env/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart Example-CI-CD-Github-Action  
          EOF
