name: Deploy first Flask App with GitHub Actions on debian server

on:
  push:
    branches:
      - main  # Déclencher l'action sur push dans main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          
          echo "${{ secrets.SSH_PRIVATA_KEY }}" > ~/.ssh/id_rsa
          chmod 600 /root/.ssh/id_rsa
          ssh-keyscan -H kascali.de >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          echo "Création du dossier .ssh"
          mkdir -p /root/.ssh
          echo "Vérification du répertoire .ssh"
          ls -al /root/.ssh  # Pour vérifier que le répertoire est bien créé
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /root/.ssh/id_rsa
          chmod 600 /root/.ssh/id_rsa
          ssh-keyscan -H kascali.de >> /root/.ssh/known_hosts
          EOF
