name: Deploy first Flask App with GitHub Actions on Debian server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH and Deploy
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.SSH_PRIVATA_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          ssh-keyscan -H kascali.de >> /home/runner/.ssh/known_hosts
          
          # Afficher les permissions du fichier id_rsa
          ls -al /home/runner/.ssh/
          
          # Tester la connexion SSH avant de lancer les commandes
          ssh -i /home/runner/.ssh/id_rsa -o StrictHostKeyChecking=no root@kascali.de 'echo "SSH connecté avec succès !"'
          
          # Déploiement
          ssh -i /home/runner/.ssh/id_rsa -o StrictHostKeyChecking=no root@kascali.de << 'EOF'
            echo "Naviguer vers le répertoire de l'application"
            cd /var/www/Example-CI-CD-Github-Action || exit 1
            echo "Tirer les dernières modifications"
            git pull origin main || exit 1
            echo "Activer l'environnement virtuel"
            source env/bin/activate || exit 1
            echo "Installer les dépendances"
            pip install -r requirements.txt || exit 1
            echo "Redémarrer le service"
            sudo systemctl restart Example-CI-CD-Github-Action || exit 1
          EOF
